actors:
  fuwari:
    image_url: /images/actors/fuwari.jpg
    name: ふわり
    url: https://twitter.com/Fuwari_WE
  yuki:
    image_url: /images/actors/yuki.jpg
    name: Yuki
    url: https://twitter.com/djotkyuki
  nemoto:
      image_url: /images/actors/unown.png
      name: ねもと
      url: #
author: fuwari
description: このPodcastは情報系企業勤務のふわりとYukiがその時のテーマについて話し合う番組です
description_long: このPodcastは情報系企業勤務のふわりとYukiがその時のテーマについて話し合う番組です。僕らならではの話題を提供していきたいと思っています。意見やフィードバックはTwitterで `#ほげほげfm` とつけてツイートしてください。フィードバックは私達の励みになります。ぜひたくさんのフィードバックをお待ちしております。
email: hogehogefm@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: ほげほげfm
itunes_podcast_url:
keywords: it
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: ほげほげfm
url: http://hogehoge.fm
